### ISSUE TITLE
Node.JS

### ISSUE THREAD

**Issue by tselishev-semen** [gavoja/aemsync#15]
Hi, I've seen that you are developing new version, which will support common.js syntax for using in Node.js.
It's very good, but your code is supported only ES6 syntax. Could you add also version for ES5?

**Comment by gavoja** [comment]
Hi,

The new version supports ES6 only so you need a (fairly) recent Node.js in order to run it. I currently do not intend to support multiple implementations; this tool is aimed mainly for the development environment, which - unlike production - should not impose any restrictions on updates. 

If for any reason you are unable to update your Node.js, please stick to v0.7.1 for the time being.

Cheers,
Michal
