### ISSUE TITLE
Package Manager clutter

### ISSUE THREAD

**Issue by ittaibaratz** [gavoja/aemsync#36]
I am using the latest version (3.0) and I've noticed it uploads every change with a new package name, leading to a clutter of packages in package manager:

Is it possible to do a cleanup, or to use the same name for the packages so that there will be only one?

Thanks!
Ittai

![image](https://user-images.githubusercontent.com/1454683/36805402-31a91704-1c72-11e8-8468-922149d843f1.png)

**Comment by gavoja** [comment]
Did you customise the package name in any way? By default, the package deployed is called `aemsync.zip` and should be overwritten every time the code is pushed.

**Comment by ittaibaratz** [comment]
Hi @gavoja , I have not customized it, however I am using AEM 6.4 (I work at Adobe), so perhaps something has changed on the AEM side. I'll take a closer look. Thanks!

**Comment by gavoja** [comment]
It would be great to understand if this is an issue in 6.4 or a potential change in behaviour. In case of the latter I would have to update the code accordingly.

**Comment by abmaonline** [comment]
Also encountered this issue since I upgraded to 6.3 SP2. It's not only the name with the guid, but it is also put in the group 'temporary':

**2018-04-16 Running aemsync 1.1.1 on AEM 6.3.1.2** (91c059b with option to watch multiple folders and provide list of items to callback on onPushEnd)
AEM 6.3.1.2, aemsync 1.1.1 (with changes)
aemsync.zip
Last installed Apr 16 | admin
Group: (none)

**2018-04-17 Installed SP2 for 6.3**

**2017-04-19 Started development using aemsync again**
AEM 6.3.2.0, aemsync 1.1.1 (with changes)
pack_ab1eeee7-dd31-4a50-8d35-063e6fdf8e02.zip
Last installed Apr 19 | admin
Group: temporary

**2017-04-28 Upgrade aemsync to 3.0.0 and apply customizations** (ccdecac with extra code like 1.1.1 and fix for micromatch parameters)
AEM 6.3.2.0, aemsync 3.0.0 (with changes)
pack_00ea1a19-892e-4480-bef5-f460575f0180.zip
Last installed Apr 28 | admin 
Group: temporary

**2017-04-30 Test with clean version 3.0.0**
AEM 6.3.2.0, aemsync 3.0.0 (ccdecac no changes)
pack_4c777cbe-2894-4324-bb29-655a16a9ec4f.zip
Last installed 18:21 | admin 
Group: 	temporary

**Comment by abmaonline** [comment]
The issue is with the version of FileVault that is part of AEM 6.3 SP2 and AEM 6.4.

Since JCRVLT-192 FileVault needs both a name and group in the properties.xml, otherwise it defaults to the pack_{guid}.zip naming for the package.

Fixed it in https://github.com/gavoja/aemsync/pull/39

This change was part of FileVault 3.1.42 and is now part of AEM 6.3 SP2 and AEM 6.4.

Commit with relevant changes: https://github.com/apache/jackrabbit-filevault/commit/da786663ea49ddbd9b276871d92661f598158c08
