### ISSUE TITLE
vs webdav

### ISSUE THREAD

**Issue by brewster1134** [gavoja/aemsync#41]
the aem project i currently work on, we watch for file changes and push individual files via webdav into crx. aemsync seems to archive any changed folders within a certain threshold of time, and upload and install a zip package via the package manager service. have these 2 approaches been compared and performance tested? was webdav considered, and if so was there any details around why the package manager approach was used?

**Comment by gavoja** [comment]
The very first draft of aemsync was webdav based, however not all JCR capabilities are exposed via WebDAV. As far as I remember WebDAV enables to copy files and directories only; that means an XML file is not decomposed to nodes and properties, but rather copied as a file. The logic to turn XML into set of nodes is a part of the VLT, so in order to leverage that, you either have to use VLT or the Package Manager.

Alternative solution is to use Sling POST Servlet, but in that case you have to handle XML decomposition yourself. That is why I ended up using Package Manager, as it is the simplest and most flexible approach (though not without drawbacks). If you find a better solution, please let me know!
